development:
  adapter: postgresql
  encoding: utf8
  database: gigiprep_development
  pool: 5
  username: jluckett
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: gigiprep_test
  pool: 5
  username: jluckett
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: gigiprep_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST